import type { DashboardStats, Call, PipelineStage } from '@/types';

export const dashboardStats: DashboardStats = {
  totalCalls: 156,
  totalCallsTrend: 12.5,
  bookingsMade: 89,
  bookingsTrend: 8.3,
  missedCallsRecovered: 34,
  missedCallsTrend: 23.1,
  revenueImpact: 45600,
  revenueTrend: 15.7,
};

export const recentCalls: Call[] = [
  {
    id: 'call-001',
    contactName: 'Maria Gonzalez',
    phone: '5551234567',
    duration: 194,
    status: 'completed',
    type: 'inbound',
    summary:
      'Customer called about a kitchen sink leak that started this morning. Scheduled a same-day appointment for leak repair. Quoted $150-$250 range.',
    transcript: [
      {
        role: 'ai',
        content:
          "Thank you for calling Flowmax Plumbing, this is your AI assistant. How can I help you today?",
        timestamp: '2026-03-28T09:14:00Z',
      },
      {
        role: 'customer',
        content:
          "Hi, I've got a leak under my kitchen sink. It started dripping this morning and it's getting worse.",
        timestamp: '2026-03-28T09:14:12Z',
      },
      {
        role: 'ai',
        content:
          "I'm sorry to hear that. A kitchen sink leak can definitely get worse quickly. Let me get you scheduled with one of our plumbers as soon as possible. Can I get your name and address?",
        timestamp: '2026-03-28T09:14:20Z',
      },
      {
        role: 'customer',
        content:
          "Sure, it's Maria Gonzalez, 4521 Elm Street.",
        timestamp: '2026-03-28T09:14:35Z',
      },
      {
        role: 'ai',
        content:
          "Thank you, Maria. I have a plumber available this afternoon between 2 and 4 PM. Kitchen sink leak repairs typically run between $150 and $250 depending on the issue. Would that work for you?",
        timestamp: '2026-03-28T09:14:45Z',
      },
      {
        role: 'customer',
        content: "Yes, that works. Thank you so much!",
        timestamp: '2026-03-28T09:15:00Z',
      },
    ],
    recordingUrl: '/recordings/call-001.wav',
    stereoRecordingUrl: '/recordings/call-001-stereo.wav',
    cost: 0.12,
    success: true,
    createdAt: '2026-03-28T09:14:00Z',
    endedAt: '2026-03-28T09:17:14Z',
  },
  {
    id: 'call-002',
    contactName: 'James Whitfield',
    phone: '5559876543',
    duration: 0,
    status: 'missed',
    type: 'inbound',
    summary: 'Missed call. Automated follow-up SMS sent with callback link.',
    transcript: [],
    cost: 0,
    success: false,
    createdAt: '2026-03-28T08:45:00Z',
  },
  {
    id: 'call-003',
    contactName: 'Patricia Chen',
    phone: '5554567890',
    duration: 247,
    status: 'completed',
    type: 'inbound',
    summary:
      'Customer needs emergency water heater replacement. Unit is 15 years old and leaking from the bottom. Scheduled next-day installation, quoted $2,800-$3,500 for 50-gallon tank replacement.',
    transcript: [
      {
        role: 'ai',
        content:
          "Thank you for calling Flowmax Plumbing. How can I assist you today?",
        timestamp: '2026-03-27T16:30:00Z',
      },
      {
        role: 'customer',
        content:
          "My water heater is leaking everywhere. There's water all over my garage floor.",
        timestamp: '2026-03-27T16:30:10Z',
      },
      {
        role: 'ai',
        content:
          "That sounds urgent. First, if you can safely reach the water heater, please turn off the gas or power supply and the cold water inlet valve. How old is your water heater?",
        timestamp: '2026-03-27T16:30:18Z',
      },
      {
        role: 'customer',
        content:
          "It's probably 15 years old. I think it's time for a new one.",
        timestamp: '2026-03-27T16:30:30Z',
      },
      {
        role: 'ai',
        content:
          "At 15 years, replacement is definitely the better option over repair. For a standard 50-gallon tank water heater, installed, you're looking at $2,800 to $3,500. We have a plumber available tomorrow morning. Would you like me to book that?",
        timestamp: '2026-03-27T16:30:40Z',
      },
      {
        role: 'customer',
        content: "Yes, please, first thing in the morning.",
        timestamp: '2026-03-27T16:30:55Z',
      },
    ],
    recordingUrl: '/recordings/call-003.wav',
    stereoRecordingUrl: '/recordings/call-003-stereo.wav',
    cost: 0.15,
    success: true,
    createdAt: '2026-03-27T16:30:00Z',
    endedAt: '2026-03-27T16:34:07Z',
  },
  {
    id: 'call-004',
    contactName: 'Robert Kim',
    phone: '5552345678',
    duration: 156,
    status: 'completed',
    type: 'outbound',
    summary:
      'Follow-up call for missed call earlier. Customer needs drain cleaning in master bathroom. Booked for Thursday afternoon.',
    transcript: [
      {
        role: 'ai',
        content:
          "Hi, this is Flowmax Plumbing returning your call. We noticed we missed you earlier. How can we help?",
        timestamp: '2026-03-27T14:00:00Z',
      },
      {
        role: 'customer',
        content:
          "Oh great, thanks for calling back. My master bathroom drain is completely clogged. Water just sits there.",
        timestamp: '2026-03-27T14:00:12Z',
      },
      {
        role: 'ai',
        content:
          "I can get that taken care of. Drain cleaning services start at $175. We have availability on Thursday between 1 and 3 PM. Does that work?",
        timestamp: '2026-03-27T14:00:22Z',
      },
      {
        role: 'customer',
        content: "Thursday afternoon is perfect.",
        timestamp: '2026-03-27T14:00:35Z',
      },
    ],
    recordingUrl: '/recordings/call-004.wav',
    cost: 0.10,
    success: true,
    createdAt: '2026-03-27T14:00:00Z',
    endedAt: '2026-03-27T14:02:36Z',
  },
  {
    id: 'call-005',
    contactName: 'Susan Taylor',
    phone: '5558765432',
    duration: 312,
    status: 'completed',
    type: 'inbound',
    summary:
      'Customer reports sewer line backup with sewage smell in basement. Marked as emergency. Dispatched plumber for same-day emergency service. Quoted $350-$800 for sewer line clearing.',
    transcript: [
      {
        role: 'ai',
        content:
          "Flowmax Plumbing, how can I help you?",
        timestamp: '2026-03-27T11:20:00Z',
      },
      {
        role: 'customer',
        content:
          "I have a really bad situation. There's sewage backing up into my basement. It smells terrible and I don't know what to do.",
        timestamp: '2026-03-27T11:20:08Z',
      },
      {
        role: 'ai',
        content:
          "I understand this is very stressful. This sounds like a sewer line backup which we treat as an emergency. I'm going to flag this as urgent and get a plumber to you as quickly as possible today. Can I get your address?",
        timestamp: '2026-03-27T11:20:18Z',
      },
      {
        role: 'customer',
        content: "7890 Oak Drive. Please hurry.",
        timestamp: '2026-03-27T11:20:30Z',
      },
      {
        role: 'ai',
        content:
          "I'm dispatching a plumber now. Sewer line clearing typically runs $350 to $800 depending on the severity. Someone will be there within 2 hours. Is there anything else I can help with?",
        timestamp: '2026-03-27T11:20:40Z',
      },
      {
        role: 'customer',
        content: "No, just please get someone here fast. Thank you.",
        timestamp: '2026-03-27T11:20:50Z',
      },
    ],
    recordingUrl: '/recordings/call-005.wav',
    stereoRecordingUrl: '/recordings/call-005-stereo.wav',
    cost: 0.19,
    success: true,
    createdAt: '2026-03-27T11:20:00Z',
    endedAt: '2026-03-27T11:25:12Z',
  },
  {
    id: 'call-006',
    contactName: 'David Martinez',
    phone: '5553456789',
    duration: 128,
    status: 'completed',
    type: 'inbound',
    summary:
      'Customer called about a running toilet that wastes water. Scheduled routine repair for next week. Quoted $100-$200.',
    transcript: [
      {
        role: 'ai',
        content:
          "Flowmax Plumbing, how may I help you today?",
        timestamp: '2026-03-26T15:45:00Z',
      },
      {
        role: 'customer',
        content:
          "My toilet keeps running. It won't stop and I think it's wasting a lot of water.",
        timestamp: '2026-03-26T15:45:10Z',
      },
      {
        role: 'ai',
        content:
          "A running toilet is a common issue and usually a quick fix. Toilet repairs typically cost between $100 and $200. We have openings next Monday or Tuesday. Which works better for you?",
        timestamp: '2026-03-26T15:45:20Z',
      },
      {
        role: 'customer',
        content: "Monday morning would be great.",
        timestamp: '2026-03-26T15:45:30Z',
      },
    ],
    recordingUrl: '/recordings/call-006.wav',
    cost: 0.08,
    success: true,
    createdAt: '2026-03-26T15:45:00Z',
    endedAt: '2026-03-26T15:47:08Z',
  },
  {
    id: 'call-007',
    contactName: 'Amanda Brooks',
    phone: '5556789012',
    duration: 0,
    status: 'missed',
    type: 'inbound',
    summary: 'Missed call during off-hours. Voicemail left about faucet installation. SMS follow-up sent.',
    transcript: [],
    cost: 0,
    success: false,
    createdAt: '2026-03-26T21:15:00Z',
  },
  {
    id: 'call-008',
    contactName: 'Michael Nguyen',
    phone: '5557890123',
    duration: 185,
    status: 'completed',
    type: 'inbound',
    summary:
      'Customer needs garbage disposal replacement. Current unit is jammed and making grinding noise. Booked for Wednesday. Quoted $250-$450 installed.',
    transcript: [
      {
        role: 'ai',
        content:
          "Thank you for calling Flowmax Plumbing. What can I do for you?",
        timestamp: '2026-03-26T10:00:00Z',
      },
      {
        role: 'customer',
        content:
          "My garbage disposal is making a horrible grinding noise and then it just stops working. I think something is stuck in there.",
        timestamp: '2026-03-26T10:00:12Z',
      },
      {
        role: 'ai',
        content:
          "It sounds like the disposal may be jammed or the motor could be failing. If it's repairable we'll fix it, but if it needs replacement, a new garbage disposal installed runs between $250 and $450. We have availability Wednesday morning. Would you like to book that?",
        timestamp: '2026-03-26T10:00:24Z',
      },
      {
        role: 'customer',
        content: "Yes, Wednesday works. Thanks!",
        timestamp: '2026-03-26T10:00:38Z',
      },
    ],
    recordingUrl: '/recordings/call-008.wav',
    cost: 0.11,
    success: true,
    createdAt: '2026-03-26T10:00:00Z',
    endedAt: '2026-03-26T10:03:05Z',
  },
];

export const pipelineStages: PipelineStage[] = [
  {
    id: 'stage-new',
    title: 'New Leads',
    contacts: [
      {
        id: 'contact-001',
        name: 'James Whitfield',
        phone: '5559876543',
        email: 'james.w@email.com',
        service: 'Unknown — missed call',
        status: 'new',
        urgency: 'routine',
        source: 'missed_call',
        createdAt: '2026-03-28T08:45:00Z',
        lastContactAt: '2026-03-28T08:45:00Z',
        notes: 'Missed call. SMS follow-up sent, awaiting response.',
      },
      {
        id: 'contact-002',
        name: 'Amanda Brooks',
        phone: '5556789012',
        email: 'amanda.b@email.com',
        service: 'Faucet installation',
        status: 'new',
        urgency: 'routine',
        source: 'missed_call',
        createdAt: '2026-03-26T21:15:00Z',
        lastContactAt: '2026-03-26T21:15:00Z',
        notes: 'Off-hours voicemail about kitchen faucet install. Needs callback.',
      },
      {
        id: 'contact-003',
        name: 'Lisa Patel',
        phone: '5551112233',
        service: 'Bathroom remodel',
        status: 'new',
        urgency: 'routine',
        source: 'website',
        createdAt: '2026-03-27T20:00:00Z',
        lastContactAt: '2026-03-27T20:00:00Z',
        notes: 'Submitted website inquiry about master bath remodel.',
      },
      {
        id: 'contact-004',
        name: 'Kevin O\'Brien',
        phone: '5554443322',
        service: 'Pipe insulation',
        status: 'new',
        urgency: 'routine',
        source: 'referral',
        createdAt: '2026-03-28T07:30:00Z',
        lastContactAt: '2026-03-28T07:30:00Z',
        notes: 'Referred by Patricia Chen. Wants pipes insulated before winter.',
      },
    ],
  },
  {
    id: 'stage-contacted',
    title: 'Contacted',
    contacts: [
      {
        id: 'contact-005',
        name: 'Robert Kim',
        phone: '5552345678',
        email: 'robert.kim@email.com',
        service: 'Drain cleaning',
        status: 'contacted',
        urgency: 'urgent',
        source: 'missed_call',
        createdAt: '2026-03-27T12:30:00Z',
        lastContactAt: '2026-03-27T14:02:36Z',
        notes: 'Returned missed call. Master bath drain clog. Booked Thursday 1-3 PM.',
      },
      {
        id: 'contact-006',
        name: 'Nancy Williams',
        phone: '5558889900',
        service: 'Water softener install',
        status: 'contacted',
        urgency: 'routine',
        source: 'inbound_call',
        createdAt: '2026-03-26T09:00:00Z',
        lastContactAt: '2026-03-27T10:00:00Z',
        notes: 'Called about hard water issues. Sent quote for water softener system.',
      },
      {
        id: 'contact-007',
        name: 'Tom Henderson',
        phone: '5553334455',
        service: 'Sump pump repair',
        status: 'contacted',
        urgency: 'urgent',
        source: 'inbound_call',
        createdAt: '2026-03-27T08:15:00Z',
        lastContactAt: '2026-03-27T14:30:00Z',
        notes: 'Sump pump making noise. Sent follow-up with pricing options.',
      },
    ],
  },
  {
    id: 'stage-qualified',
    title: 'Qualified',
    contacts: [
      {
        id: 'contact-008',
        name: 'David Martinez',
        phone: '5553456789',
        email: 'dmartinez@email.com',
        service: 'Toilet repair',
        status: 'qualified',
        urgency: 'routine',
        source: 'inbound_call',
        createdAt: '2026-03-26T15:45:00Z',
        lastContactAt: '2026-03-26T15:47:08Z',
        notes: 'Running toilet. Scheduled Monday morning. Confirmed $100-$200 range.',
      },
      {
        id: 'contact-009',
        name: 'Michael Nguyen',
        phone: '5557890123',
        email: 'mnguyen@email.com',
        service: 'Garbage disposal replacement',
        status: 'qualified',
        urgency: 'routine',
        source: 'inbound_call',
        createdAt: '2026-03-26T10:00:00Z',
        lastContactAt: '2026-03-26T10:03:05Z',
        notes: 'Jammed disposal. Booked Wednesday. Budget approved for replacement.',
      },
      {
        id: 'contact-010',
        name: 'Jennifer Adams',
        phone: '5556667788',
        email: 'jen.adams@email.com',
        service: 'Tankless water heater upgrade',
        status: 'qualified',
        urgency: 'routine',
        source: 'website',
        createdAt: '2026-03-25T12:00:00Z',
        lastContactAt: '2026-03-26T16:00:00Z',
        notes: 'Wants to upgrade from tank to tankless. Quote sent: $3,200-$4,500.',
      },
    ],
  },
  {
    id: 'stage-booked',
    title: 'Booked',
    contacts: [
      {
        id: 'contact-011',
        name: 'Maria Gonzalez',
        phone: '5551234567',
        email: 'maria.g@email.com',
        service: 'Kitchen sink leak repair',
        status: 'booked',
        urgency: 'urgent',
        source: 'inbound_call',
        createdAt: '2026-03-28T09:14:00Z',
        lastContactAt: '2026-03-28T09:17:14Z',
        notes: 'Same-day appointment. Kitchen sink leak. Plumber en route 2-4 PM.',
      },
      {
        id: 'contact-012',
        name: 'Patricia Chen',
        phone: '5554567890',
        email: 'p.chen@email.com',
        service: 'Water heater replacement',
        status: 'booked',
        urgency: 'emergency',
        source: 'inbound_call',
        createdAt: '2026-03-27T16:30:00Z',
        lastContactAt: '2026-03-27T16:34:07Z',
        notes: 'Emergency water heater replacement. Scheduled tomorrow 8 AM. 50-gal tank.',
      },
      {
        id: 'contact-013',
        name: 'Susan Taylor',
        phone: '5558765432',
        email: 'susan.t@email.com',
        service: 'Sewer line clearing',
        status: 'booked',
        urgency: 'emergency',
        source: 'inbound_call',
        createdAt: '2026-03-27T11:20:00Z',
        lastContactAt: '2026-03-27T11:25:12Z',
        notes: 'Emergency sewer backup. Plumber dispatched same day.',
      },
      {
        id: 'contact-014',
        name: 'Carlos Rivera',
        phone: '5552223344',
        service: 'Whole-house repipe',
        status: 'booked',
        urgency: 'routine',
        source: 'referral',
        createdAt: '2026-03-22T10:00:00Z',
        lastContactAt: '2026-03-26T09:00:00Z',
        notes: 'Full copper repipe. Quote accepted at $8,500. Scheduled next week.',
      },
      {
        id: 'contact-015',
        name: 'Emily Zhao',
        phone: '5559990011',
        email: 'emily.z@email.com',
        service: 'Gas line installation',
        status: 'booked',
        urgency: 'routine',
        source: 'website',
        createdAt: '2026-03-24T14:00:00Z',
        lastContactAt: '2026-03-27T11:00:00Z',
        notes: 'New gas line for outdoor grill. Permit pulled. Scheduled Friday.',
      },
    ],
  },
  {
    id: 'stage-completed',
    title: 'Completed',
    contacts: [
      {
        id: 'contact-016',
        name: 'Frank Thompson',
        phone: '5551119988',
        service: 'Faucet replacement',
        status: 'completed',
        urgency: 'routine',
        source: 'inbound_call',
        createdAt: '2026-03-20T09:00:00Z',
        lastContactAt: '2026-03-23T16:00:00Z',
        notes: 'Kitchen faucet replaced. Delta single-handle. Customer satisfied. Invoice paid.',
      },
      {
        id: 'contact-017',
        name: 'Rachel Green',
        phone: '5557776655',
        email: 'rachel.g@email.com',
        service: 'Drain cleaning',
        status: 'completed',
        urgency: 'urgent',
        source: 'inbound_call',
        createdAt: '2026-03-21T08:30:00Z',
        lastContactAt: '2026-03-22T14:00:00Z',
        notes: 'Severe kitchen drain clog. Hydro-jetted. $325 collected. 5-star review received.',
      },
      {
        id: 'contact-018',
        name: 'William Park',
        phone: '5554448877',
        service: 'Toilet installation',
        status: 'completed',
        urgency: 'routine',
        source: 'referral',
        createdAt: '2026-03-19T11:00:00Z',
        lastContactAt: '2026-03-24T10:00:00Z',
        notes: 'Two new Kohler toilets installed in master and guest bath. $1,100 collected.',
      },
      {
        id: 'contact-019',
        name: 'Diana Ross',
        phone: '5553332211',
        email: 'diana.r@email.com',
        service: 'Water heater repair',
        status: 'completed',
        urgency: 'urgent',
        source: 'missed_call',
        createdAt: '2026-03-18T07:00:00Z',
        lastContactAt: '2026-03-20T15:00:00Z',
        notes: 'Thermocouple replaced on gas water heater. $180 collected. Follow-up satisfied.',
      },
      {
        id: 'contact-020',
        name: 'Chris Evans',
        phone: '5558887766',
        service: 'Pipe burst repair',
        status: 'completed',
        urgency: 'emergency',
        source: 'inbound_call',
        createdAt: '2026-03-17T06:30:00Z',
        lastContactAt: '2026-03-18T12:00:00Z',
        notes: 'Emergency burst pipe in basement. Repaired and section replaced. $750 collected.',
      },
      {
        id: 'contact-021',
        name: 'Angela Murphy',
        phone: '5552221100',
        service: 'Shower valve replacement',
        status: 'completed',
        urgency: 'routine',
        source: 'website',
        createdAt: '2026-03-16T13:00:00Z',
        lastContactAt: '2026-03-21T11:00:00Z',
        notes: 'Moen shower valve replaced. Customer happy with water pressure improvement. $290 collected.',
      },
    ],
  },
];

export const callsChartData = [
  { date: 'Mar 14', calls: 8, bookings: 4 },
  { date: 'Mar 15', calls: 12, bookings: 7 },
  { date: 'Mar 16', calls: 6, bookings: 3 },
  { date: 'Mar 17', calls: 14, bookings: 9 },
  { date: 'Mar 18', calls: 11, bookings: 6 },
  { date: 'Mar 19', calls: 9, bookings: 5 },
  { date: 'Mar 20', calls: 13, bookings: 8 },
  { date: 'Mar 21', calls: 10, bookings: 6 },
  { date: 'Mar 22', calls: 7, bookings: 4 },
  { date: 'Mar 23', calls: 15, bookings: 10 },
  { date: 'Mar 24', calls: 12, bookings: 7 },
  { date: 'Mar 25', calls: 11, bookings: 6 },
  { date: 'Mar 26', calls: 14, bookings: 8 },
  { date: 'Mar 27', calls: 16, bookings: 9 },
];

// Sparkline data for stat card mini charts (7 data points each)
export const sparklineData = {
  totalCalls: [
    { v: 22 }, { v: 18 }, { v: 24 }, { v: 20 }, { v: 26 }, { v: 23 }, { v: 28 },
  ],
  bookings: [
    { v: 12 }, { v: 14 }, { v: 11 }, { v: 16 }, { v: 13 }, { v: 15 }, { v: 18 },
  ],
  missedRecovered: [
    { v: 5 }, { v: 8 }, { v: 4 }, { v: 7 }, { v: 6 }, { v: 9 }, { v: 7 },
  ],
  revenue: [
    { v: 6200 }, { v: 7400 }, { v: 5800 }, { v: 8100 }, { v: 7200 }, { v: 9500 }, { v: 8800 },
  ],
};

// 7-day and 30-day chart data
export const callsChartData7Days = [
  { date: 'Mar 22', calls: 7, bookings: 4 },
  { date: 'Mar 23', calls: 15, bookings: 10 },
  { date: 'Mar 24', calls: 12, bookings: 7 },
  { date: 'Mar 25', calls: 11, bookings: 6 },
  { date: 'Mar 26', calls: 14, bookings: 8 },
  { date: 'Mar 27', calls: 16, bookings: 9 },
  { date: 'Mar 28', calls: 19, bookings: 12 },
];

export const callsChartData30Days = [
  { date: 'Feb 27', calls: 10, bookings: 5 },
  { date: 'Feb 28', calls: 13, bookings: 7 },
  { date: 'Mar 1', calls: 8, bookings: 4 },
  { date: 'Mar 2', calls: 11, bookings: 6 },
  { date: 'Mar 3', calls: 9, bookings: 5 },
  { date: 'Mar 4', calls: 14, bookings: 8 },
  { date: 'Mar 5', calls: 12, bookings: 7 },
  { date: 'Mar 6', calls: 7, bookings: 3 },
  { date: 'Mar 7', calls: 15, bookings: 9 },
  { date: 'Mar 8', calls: 10, bookings: 6 },
  { date: 'Mar 9', calls: 13, bookings: 7 },
  { date: 'Mar 10', calls: 11, bookings: 6 },
  { date: 'Mar 11', calls: 9, bookings: 5 },
  { date: 'Mar 12', calls: 16, bookings: 10 },
  { date: 'Mar 13', calls: 14, bookings: 8 },
  { date: 'Mar 14', calls: 8, bookings: 4 },
  { date: 'Mar 15', calls: 12, bookings: 7 },
  { date: 'Mar 16', calls: 6, bookings: 3 },
  { date: 'Mar 17', calls: 14, bookings: 9 },
  { date: 'Mar 18', calls: 11, bookings: 6 },
  { date: 'Mar 19', calls: 9, bookings: 5 },
  { date: 'Mar 20', calls: 13, bookings: 8 },
  { date: 'Mar 21', calls: 10, bookings: 6 },
  { date: 'Mar 22', calls: 7, bookings: 4 },
  { date: 'Mar 23', calls: 15, bookings: 10 },
  { date: 'Mar 24', calls: 12, bookings: 7 },
  { date: 'Mar 25', calls: 11, bookings: 6 },
  { date: 'Mar 26', calls: 14, bookings: 8 },
  { date: 'Mar 27', calls: 16, bookings: 9 },
  { date: 'Mar 28', calls: 19, bookings: 12 },
];
